version: '3'
services:
  ### Postgres database for customers
  db-customers:
    container_name: db-customers
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_customers
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### PostgreSQL for Accounts Service
  db-accounts:
    container_name: db-accounts
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_accounts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### PostgreSQL for Transactions Service
  db-transactions:
    container_name: db-transactions
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_transactions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ### Postgres database for customers integration test
  db-customers-test:
    container_name: db-customers-test
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_customers-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434
