services:
  ### Postgres database for customers
  db-customers:
    container_name: db-customers
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_customers
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### PostgreSQL for Accounts Service
  db-accounts:
    container_name: db-accounts
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_accounts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### PostgreSQL for Transactions Service
  db-transactions:
    container_name: db-transactions
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_transactions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ### Postgres database for customers integration test
  db-customers-test:
    container_name: db-customers-test
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_customers-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434

  ### Customers Service
  customers-service:
    build:
      context: .
      dockerfile: ./customers-service/Dockerfile
    depends_on:
      - db-customers
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-customers:5431/ms_customers
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    restart: unless-stopped

  ### Accounts Service
  accounts-service:
    build:
      context: .
      dockerfile: ./accounts-service/Dockerfile
    depends_on:
      - db-accounts
      - customers-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-accounts:5432/ms_accounts
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=docker
      # Configura la URL del servicio customers para Feign client
      - FEIGN_CLIENT_CUSTOMERS_SERVICE_URL=http://customers-service:8082
    ports:
      - "8083:8083"
    restart: unless-stopped

  ### Transactions Service
  transactions-service:
    build:
      context: .
      dockerfile: ./transactions-service/Dockerfile
    depends_on:
      - db-transactions
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-transactions:5433/ms_transactions
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    restart: unless-stopped
